INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (1, 'L''inventaire <strong>INV-0063-22 vient de faire l''objet d''une régularisation</strong>, merci de vérifier', 'danger', '#!/list-inventaire', null, '2022-07-23 17:06:27', '2022-07-23 17:06:27', null, null, null, null, 'Inventaire Régularisée !!!');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (2, 'La depense N°<strong>1325 est en attente de validation</strong>, merci de vérifier', 'info', '#!/list-depense', null, '2022-07-23 18:03:42', '2022-07-23 18:03:42', null, null, null, null, 'Notification HH');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (3, '<i class=''fa fa-exclamation-triangle''></i> Pour rappel<br><br><i class=''fa fa-shopping-basket''></i> <u>LES COMMANDES</u>: <strong>CMD-005911-22</strong><br><br><i class=''fa fa-bags-shopping''></i> <u>LES PRODUITS</u>:<br><i class=''fa fa-arrow-right''></i> 2 x RIDEAU OCCULTANT - Bleu marine - 200x260cm => CMD-005911-22<br><br> doivent être récupérés aujourd''hui <br>', 'warning', '#!/list-commande', null, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null, null, null, 'Rappel Livraison !!!');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (4, '<strong>L''import du fichier excel est en cours</strong>,<br>Vous serez notifié une fois le traitement terminé', 'info', '#!/list-produit', null, '2022-07-24 14:11:53', '2022-07-24 14:11:53', 2, 2, null, null, null);
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (5, 'L''inventaire <strong>INV-0070-22 vient de faire l''objet d''une régularisation</strong>, merci de vérifier', 'danger', '#!/list-inventaire', null, '2022-07-25 15:43:38', '2022-07-25 15:43:38', null, null, null, null, 'Inventaire Régularisée !!!');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (6, 'La depense N°<strong>1331 est en attente de validation</strong>, merci de vérifier', 'info', '#!/list-depense', null, '2022-07-25 16:51:51', '2022-07-25 16:51:51', null, null, null, null, 'Notification HH');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (7, 'La depense N°<strong>1333 vient d''être effectuée</strong>, merci de vérifier', 'info', '#!/list-depense', null, '2022-07-25 17:11:43', '2022-07-25 17:11:43', null, null, null, null, 'Notification HH');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (8, 'Le produit <strong>REMBOURRAGE COUSSIN</strong> pour la commande <strong>CMD-005450-22</strong> a été marqué <strong>« Récupéré »</strong>, merci de vérifier', 'info', '#!/list-commande', null, '2022-07-26 10:57:07', '2022-07-26 10:57:07', null, null, null, null, 'Produit récupéré');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (9, 'Le produit <strong>DRAP HOUSSE UNI COTON SATIN 300 FILS</strong> pour la commande <strong>CMD-005450-22</strong> a été marqué <strong>« Récupéré »</strong>, merci de vérifier', 'info', '#!/list-commande', null, '2022-07-26 10:57:47', '2022-07-26 10:57:47', null, null, null, null, 'Produit récupéré');
INSERT INTO public.notifs (id, message, toast, link, deleted_at, created_at, updated_at, created_at_user_id, updated_at_user_id, page_id, module_id, title) VALUES (10, 'Le produit <strong>DRAP PLAT UNI COTON SATIN 300 FILS</strong> pour la commande <strong>CMD-005450-22</strong> a été marqué <strong>« Récupéré »</strong>, merci de vérifier', 'info', '#!/list-commande', null, '2022-07-26 10:57:54', '2022-07-26 10:57:54', null, null, null, null, 'Produit récupéré');

INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (1, 8, 1, 2, false, '2022-07-25 17:11:43', '2022-07-25 17:11:43', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (2, 9, 1, 2, false, '2022-07-25 17:11:43', '2022-07-25 17:11:43', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (3, 10, 1, 2, false, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (4, 7, 1, 2, false, '2022-07-25 17:11:43', '2022-07-25 17:11:43', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (5, 10, 1, 2, false, '2022-07-25 17:11:43', '2022-07-25 17:11:43', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (6, 5, 1, 2, false, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (7, 4, 1, 2, false, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (8, 3, 1, 2, false, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (9, 2, 1, 2, false, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null);
INSERT INTO public.notif_perm_users (id, notif_id, permission_id, user_id, view, created_at, updated_at, created_at_user_id, updated_at_user_id) VALUES (10, 1, 1, 2, false, '2022-07-25 06:00:02', '2022-07-25 06:00:02', null, null);


SELECT setval(pg_get_serial_sequence('notifs', 'id'), (SELECT MAX(id) FROM notifs)+1);
SELECT setval(pg_get_serial_sequence('notif_perm_users', 'id'), (SELECT MAX(id) FROM notif_perm_users)+1);

--update notif_perm_users set view = false where 1=1;
